### ISSUE TITLE
Strange DELETE operation when pulling variants

### ISSUE THREAD

**Issue by awebber-chl** [aligent/bigcommerce-v3-api-php-client#134]
Hi there. I am trying to pull variants for all the products in my sandbox store and was surprised to see the following error when running a $variantsResponse->getProductVariants() operation:

```[02-Jun-2022 10:13:41 UTC] PHP Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `DELETE https://api.bigcommerce.com/stores/1x2q3tkivy/v3/catalog/products/736/variants/1522` resulted in a `404 Not Found` response:
{"status":404,"code":22001,"title":"No variants with id 1522 found for product id 736","type":"https://developer.bigcomm (truncated...)```

Is there a valid reason why the client would be trying to delete variants when performing a lookup?

**Comment by jswift** [comment]
As in when you call this function it does a delete? Not sure how that would happen, the code is very simple:
https://github.com/aligent/bigcommerce-v3-api-php-client/blob/main/src/BigCommerce/ResponseModels/Product/ProductVariantResponse.php#L16

Have you got an example of the code that triggered this?

**Comment by jswift** [comment]
I've push a branch with some tests to ensure there is no delete request in the stack (https://github.com/aligent/bigcommerce-v3-api-php-client/blob/fix/134-errant-delete-method/tests/BigCommerce/Api/Catalog/Products/VariantsApiTest.php#L30).

I cannot reproduce any way that you would be able to generate a delete with a request like the example below.

```php
$variantResponse = $client->catalog()->product(123)->variant(456)->get();
```

**Comment by awebber-chl** [comment]
Here is the code I'm using to pull products, variants and modifiers:
```
    $api = new BigCommerce\ApiV3\Client(urldecode(get_option('bc_store_hash')), urldecode(get_option('bc_client_id')), urldecode(get_option('bc_access_token')));

    //$productsResponse = $api->catalog()->products()->getAllPages(['is_visible' => true]);
    $productsResponse = $api->catalog()->products()->getAllPages();
    if ( $productsResponse )
    {
        error_log( "Found {$productsResponse->getPagination()->total} products");
        $products = $productsResponse->getProducts();
        if ( is_array($products) && count($products) > 0 )
        {
            foreach($products as $index=>$product)
            {
                $product_id = persist_model_entry($product,'product',$product_transforms);
                try {
                    $variantResponse = $api->catalog()->product($product->id)->variants()->getAll(); 
                    $variants = $variantResponse->getProductVariants();
                    foreach ($variants as $key => $variant) {
                        persist_model_entry($variant,'variant',$variant_transforms,$product_id,'variants');
                    }

                    $modifierResponse = $api->catalog()->product($product->id)->modifiers()->getAll();
                    $modifiers = $modifierResponse->getProductModifiers();
                    foreach ($modifiers as $modifier) {
                        persist_model_entry($modifier,'modifier',$modifier_transforms,$product_id,'modifiers');
                    }
                } catch (Exception $e) {
                    error_log($e->getMessage());
                }
            }
        }
    }
```

**Comment by jswift** [comment]
I've run that through a test and confirmed there's no DELETE requests generated, do you have a stack trace (e.g. `$e->getTraceAsString();` of the exception so we can see the call stack?

FYI you don't need the lines `if ( $productsResponse )` and `if ( is_array($products) && count($products) > 0 )`, they are redundant as you'll always receive a response object unless an exception is thrown and products will always be an array.

**Comment by awebber-chl** [comment]
Thank you for the FYI 😊 

OK I know what happened now. I had some nearby test code that I accidentally left uncommented out in which someone asked me to delete specific variants for a product. My apologies for taking up your valuable time with my sloppiness.

**Comment by jswift** [comment]
No worries, thanks for updating! No wasted time, I've improved some tests :)
