### ISSUE TITLE
ResourceModels/Catalog/Product/Product.php $preorder_release_date type

### ISSUE THREAD

**Issue by cchan84** [aligent/bigcommerce-v3-api-php-client#162]
Hi,

src/BigCommerce/ResourceModels/Catalog/Product/Product.php:70
`public ?object $preorder_release_date;`

should this be
`public ?string $preorder_release_date;` ?

From BigCommerce API reference
`preorder_release_date string<date-time>`
https://developer.bigcommerce.com/api-reference/6fe995bba597e-get-a-product

Thanks

**Comment by jswift** [comment]
Yes I believe so
