### ISSUE TITLE
Is this client still the best approach?

### ISSUE THREAD

**Issue by sam-ecomdev** [aligent/bigcommerce-v3-api-php-client#170]
Quick question to any contributor.  It has been a while since there have been any significant changes to this API client.  Is it advisable to use this client or should I just auto generate a client using Swagger Codegen? For example I can see that there is no 'images' property in the ResourceModels\Catalog\Product\Product... but the BigCommerce API does allow you to send images through when creating a product without needing a seperate call to the ProductImagesApi.

Is there value in using (and possibly improving) this client or is there a better approach in 2023?

**Comment by Ctucker9233** [comment]
Have you found a better one?

**Comment by jswift** [comment]
Apologies we've been dormant for a little while, we are still actively supporting this library. You certainly can generate your own client from swagger, although in our experience with this api that didn't always work and resulted in a client that was not easy to use. 

Our goal was to match the layout of the library with the API documentation so it should be very quick to use. Whether it's the best approach for your case I can't answer.

I'll create a feature request for adding Product->images directly.
