### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by Ctucker9233** [aligent/bigcommerce-v3-api-php-client#171]
Running this client works like a charm, however, I'm getting quite a few of these deprecation warnings:

 deprecation.INFO: Deprecated: Creation of dynamic property BigCommerce\ApiV3\ResourceModels\Catalog\Brand\Brand::$page_title is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Creation of dynamic property BigCommerce\\ApiV3\\ResourceModels\\Catalog\\Brand\\Brand::$page_title is deprecated at /app/vendor/aligent/bigcommerce-api-client/src/BigCommerce/ResourceModels/ResourceModel.php:20)"} []

**Comment by jswift** [comment]
That means the property has been missed from the class, I'll create a fix shortly
