### ISSUE TITLE
Creation of dynamic properties (deprecated in PHP8)

### ISSUE THREAD

**Issue by TroggTech** [aligent/bigcommerce-v3-api-php-client#201]
Every time I access a product and other items I get a bunch of these errors:

`PHP Deprecated:  Creation of dynamic property BigCommerce\ApiV3\ResourceModels\Catalog\Product\Product::$tax_class_id is deprecated in /app/vendor/aligent/bigcommerce-api-client/src/BigCommerce/ResourceModels/ResourceModel.php on line 20`

**Comment by jswift** [comment]
Looks like the property is missing in `ResourceModel/Product`, just checking if there's any others that have been added.
