### ISSUE TITLE
Update Product Variant

### ISSUE THREAD

**Issue by base64bits** [aligent/bigcommerce-v3-api-php-client#31]
Thanks for creating such awesome library love it so far, I am just having a trouble updating a Product Variant, I can update products no problem.

I know this is not the place for this, but I found no other way to ask.

Thanks.

**Comment by jswift** [comment]
Glad you're enjoying it! I'm away at the moment so I can't do a test case, but what is the error? Do you have some code to reproduce and I'll run it against a test store.

**Comment by base64bits** [comment]
Happy new year and thanks for reply, I cannot reproduce an error since I cannot even come up with the correct syntax to update a product variant, I looked over the tests and found nothing that updates a variant, I tried different combinations and looked at the different classes but I could not get it.

**Comment by jswift** [comment]
I’ll try and get some test code written this week for you

**Comment by jswift** [comment]
Thanks to @Zigr1 this has been fixed and documented in the attached pull request

**Comment by jswift** [comment]
Fixed in 1.1.0
