### ISSUE TITLE
Fetching visible products throws a fatal access level error

### ISSUE THREAD

**Issue by aligent-skumar** [aligent/bigcommerce-v3-api-php-client#39]
Trying to fetch all the visible products:

`$products = $bigCommerceApi->catalog()->products()->getAllPages([ProductsApi::FILTER_INCLUDE_FIELDS => 'retail_price,sku'])->getProducts();`

throws the error below:
    
`Fatal error: Access level to BigCommerce\ApiV3\Api\Catalog\ProductsApi::multipleResourcesEndpoint() must be public (as in class BigCommerce\ApiV3\Api\Generic\ResourceWithBatchUpdateApi) in /usr/src/myapp/vendor/aligent/bigcommerce-api-client/src/BigCommerce/Api/Catalog/ProductsApi.php on line 95`

**Comment by jswift** [comment]
I can replicate this problem in PHP 7.4.12
It does not occur in PHP 8.0.0
