### ISSUE TITLE
Support for carts endpoint

### ISSUE THREAD

**Issue by kishan93** [aligent/bigcommerce-v3-api-php-client#43]
currently, there is no way to access the carts endpoint

- cart id is a string but `V3ApiBase` only allows int as id
- cart item parent id is a string but `V3ApiBase` only allows int as parent id

**Comment by kishan93** [comment]
I have already done the code for the carts endpoint. I can refactor, add tests and create PR.
do you have any plans for carts endpoint support?

**Comment by jswift** [comment]
We plan to eventually cover everything, and we always welcome pull requests! 

A few of the V3 resources use a UUID format id instead of int, for example [ThemesApi](https://github.com/aligent/bigcommerce-v3-api-php-client/blob/main/src/BigCommerce/Api/Themes/ThemesApi.php).

**Comment by jswift** [comment]
I had a look at your fork and see you've removed the type from the id, making it a variant. Whilst this makes sense I'd like to avoid this and keep it consistent, so I'll push a version that matches the ThemesApi and other non-integer based apis
