### ISSUE TITLE
Use parameters in product call

### ISSUE THREAD

**Issue by Yorgv** [aligent/bigcommerce-v3-api-php-client#46]
First of all, big thanks for creating this package!

Secondly, I was wondering if there is a way to include things like variations and images when getting a product from the catalog API.

Currently, I am able to get a product by doing
`$this->client->catalog()->product($id)->get()->getProduct();` 
which returns a Catalog\Product\Product. But I don't see any possibility on adding extra parameters on this call. 

According to the docs there are 3 query parameters possible:
[docs](https://developer.bigcommerce.com/api-reference/store-management/catalog/products/getproductbyid)

Is it possible for me to add these queries to my call?

Thanks in advance!

**Comment by jswift** [comment]
Glad you like it! You're right, that functionality has been overlooked and it's not possible currently. Hopefully I'll have a chance to do this over the next week, thanks for the suggestion.
