### ISSUE TITLE
getting 404 on Scripts API

### ISSUE THREAD

**Issue by kishan93** [aligent/bigcommerce-v3-api-php-client#55]
Typo on the `ScriptsApi` Class constants for endpoints.

single resource endpoint `SCRIPT_ENDPOINT` has an invalid value
multi-resource endpoint `SCRIPTS_ENDPOINT` has an invalid value

**Comment by kishan93** [comment]
I have fixed the issue I will create PR.

**Comment by jswift** [comment]
Thanks for this, I'll push a new release including this fix shortly.
