### ISSUE TITLE
Add brand_name support in product resource model

### ISSUE THREAD

**Issue by guillaume-sarramegna** [aligent/bigcommerce-v3-api-php-client#99]
Hi,

In BigCommerce Product API, especially `POST /catalog/products`, we have the ability to attach a brand directly to a product by giving its name.

> brand_name or brand_id
string
The brand can be created during a product PUT or POST request. If the brand already exists then the product will be added. If not the brand will be created and the product added. If using brand_name it performs a fuzzy match and adds the brand. eg. “Common Good” and “Common good” are the same. Brand name does not return as part of a product response. Only the brand_id.

[Source](https://developer.bigcommerce.com/api-reference/store-management/catalog/products/createproduct)

Thus, I would like to add the `$brand_name` attribute in `src/BigCommerce/ResourceModels/Catalog/Product/Product.php`.

I saw you have a documentation to update too, but I couldn't figure out how to do it by using a command line. Could you help me on this point ?

Regards,

Guillaume

**Comment by jswift** [comment]
The documentation will be regenerated when the next version is created, I think adding that explanation to the property in the model would be good because it's not very intuitive (especially that it doesn't return brand_name!)

**Comment by guillaume-sarramegna** [comment]
PR updated and ready for review
